### ISSUE TITLE
Unexpected behaviour for `run_at` and `run_in`

### ISSUE THREAD

**Issue by igorrKurr** [SchedEx/SchedEx#2]
Hello,

issue is following: after scheduling any anonymous function or mfa to run at certain time with `run_at` method, it runs 4 times instead of 1.
And similar issue with `run_in`, but instead of 4 times it keeps running continuously.

Here is small demo that reproduces issues - https://github.com/igorrKurr/schedex_issue_demo.
To see the issue, run it with `iex` and use `SchedexTest.test_run_at` or `SchedexTest.test_run_in`.

**Comment by ghost** [comment]
Hi, I'm not the author but I'm evaluating ScheEx and your issue raised my curiosity. I tried you code and it works as you said.

However I'm not sure that `SchedexTest.test_run_at` or `SchedexTest.test_run_in` are meant to be supervised like this. I tried to call them directly, without a supervisor, and they work as expected. If you look carefully at the README you'll see that the example using a supervisor uses only `SchedEx.run_every`. 

In the case of `SchedexTest.test_run_in` I think what happens is that the process started dies once it has run your callback function and your supervisor restarts it immediately. You can see with the Erlang observer (started with `:observer.start()` in Iex) that the pid keeps changing after each call to our callback function.

In the case of `SchedexTest.test_run_at`, I have to idea why it runs 4 times, but calling directly doesn't trigger this behaviour...

**Comment by mtrudel** [comment]
Apologies for my tardy response - somehow this issue got past me. 

What @amarandon describes is in fact exactly what is happening; the methods you're calling aren't generally intended to run within a supervised context. You're seeing them fire four times because `DynamicSupervisor` will restart a child 3 times by default (if you add `max_restarts: 10` to your `DynamicSupervisor` startup in `application.ex` you'll see the messages appear 11 times). 

To illustrate 'correct' use of SchedEx, it is useful to consider the two principal use cases for the library:

The first is to schedule recurring jobs where the notion of supervision and restarting makes sense. This is accomplished via `SchedEx.run_every` (or  less frequently `SchedEx.run_in` with `repeat: true` as an option). These processes are meant to be long-running and have well defined semantics for restart, and so should absolutely be supervised as you do in your example. Your `test_run_every` function is a good example of this use case. 

The second use case is to fire off periodic 'one-shot' timers via the use of `SchedEx.run_in` or `SchedEx.run_at`. These cases are generally meant to be used in an unsupervised context, since it's not always well defined what it means to restart such a job if it crashes. Idiomatic use of SchedEx in this case is to take the 'let it crash' approach and intentionally bring down the parent context if that happens, but I completely recognize that may not be totally clear from the examples in README. I'll amend. 

Thanks for the report!

**Comment by igorrKurr** [comment]
@amarandon @mtrudel thanks guys! Makes perfect sense.
