### ISSUE TITLE
Simulating Exponential Distribution Arrivals

### ISSUE THREAD

**Issue by mazz** [SchedEx/SchedEx#9]
Based on: `https://preshing.com/20111007/how-to-generate-random-timings-for-a-poisson-process/`

I made a trivial module that will calculate the next relative arrival time, however I'm calling `SchedEx.run_in()` recursively. It just hangs after the second call. Any suggestions how to use SchedEx in this manner?

```
defmodule Schedapp.Guy do
  use GenServer
  require Logger


  def start_link(arg) do
    GenServer.start_link(__MODULE__, arg, name: __MODULE__)
  end

  def init(_arg) do
    do_something()
    {:ok, %{}}
  end

  def do_something do
    Logger.info("do_something")
    random_number = :rand.uniform()
    earthquake_lambda = (1/40)

    # * 100 instead of * 1000 to speed things up
    rate = (-:math.log(1.0 - random_number) / earthquake_lambda) * 100

    Logger.info("random_number: #{random_number}")
    Logger.info("rate: #{rate}")
    Logger.info("round(rate): #{round(rate)}")
    SchedEx.run_in(__MODULE__, :do_something, [], round(rate))
  end

end

```

output:
```
•100% ➜ iex -S mix
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Compiling 1 file (.ex)

22:14:39.266 [info]  do_something
 
22:14:39.271 [info]  random_number: 0.27220302718058453
 
22:14:39.271 [info]  rate: 1270.9326126819883

22:14:39.271 [info]  round(rate): 1271
Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
22:14:40.547 [info]  do_something
 
22:14:40.547 [info]  random_number: 0.36496982652209264

22:14:40.547 [info]  rate: 1816.3310557212515

22:14:40.547 [info]  round(rate): 1816

<HANGS>
```

**Comment by mtrudel** [comment]
`SchedEx.run_in`fires up a separate process to run the given mfa in, and exits once that function is complete (though, in this case, after it schedules the 3rd invocation of `do_something`). Because of the (intentional) way SchedEx handles process termination, when the originating process terminates, the scheduled task will as well. In other words:

1. Your app (PID A) starts your GenServer
2. GenServer (PID B) runs `init` and, in turn, `do_something`. 
3. This invocation starts up a SchedEx job (PID C) to run `do_something` after a delay. PID B sticks around because it's running in a GenServer.
4. After this delay, the SchedEx hosted `do_something` call starts another SchedEx job (PID D) to run `do_something` after a delay
5. PID C then terminates, and takes PID D along with it. 

There are several approaches to take to accomplish what you want, in rough order of likely correctness:

1. Use an idiomatic `Process.send_after` based recurrence pattern to call back into your GenServer and have subsequent runs of do_something all execute within the GenServer process.
2. Use SchedEx's [TimeScales](https://github.com/SchedEx/SchedEx#testing) along with a repeating SchedEx job to dynamically change delay intervals between subsequent jobs.
3. Unlink the SchedEx jobs from the current process before completed do_something. This will cause every do_something call to create / tear down a process, which is likely not what you want.

Hope this helps!

**Comment by mazz** [comment]
Thanks, that does help. I will take Door 1! Hopefully others can see my mistakes and learn. Takes time to stop the “shared state” way of thinking.
